name = "edge-gateway"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
ORIGIN_BASE_URL = "https://edge-compute-lab.onrender.com"
ORIGIN_DEFAULT = "https://edge-compute-lab.onrender.com"
ORIGIN_EU = "https://edge-compute-lab.onrender.com"
ORIGIN_US = "https://edge-compute-lab.onrender.com"
ORIGIN_V2 = "https://edge-compute-lab-1.onrender.com"

EDGE_API_KEY = "dev-secret"
CANARY_RATIO = "0.1"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimitCounter"

[[migrations]]
tag = "v1"
new_classes = ["RateLimitCounter"]

[[kv_namespaces]]
binding = "FEATURE_FLAGS"
id = "c8dbc2d0da0443ae9cd8371d8489bbd2"
preview_id = "c8dbc2d0da0443ae9cd8371d8489bbd2"
